### ISSUE TITLE
Redirects to a blank page (http://unicornucopia.tech.cornell.edu)

### ISSUE THREAD

**Issue by franksli** [cornelltech/idea-hopper-client#15]
When I use this url (after signing in):
http://unicornucopia.tech.cornell.edu/

It redirects me to (which is a blank page):
http://unicornucopia.tech.cornell.edu/#/ideas/create

instead of:
http://unicornucopia.tech.cornell.edu/#/ideas/ideas/create

**Comment by AVatch** [comment]
Good catch!

**Comment by AVatch** [comment]
Fixed the redirect issue
