### ISSUE TITLE
Comments not displayed in My Feedback column

### ISSUE THREAD

**Issue by shawnbr** [cornelltech/idea-hopper-client#28]
Only one of my comments are currently displayed though I have made many more.

**Comment by AVatch** [comment]
Good point - thanks, I will look into it

**Comment by gregbrill** [comment]
I'm having a similar issue. I think 2 of 4 comments are showing in my feedback.

**Comment by AVatch** [comment]
To be clear: 

The reason you are not seeing the ideas you commented on is because the "My Feedback" list on your account page only renders ideas you unicorned.

**Comment by shawnbr** [comment]
Hmm... given that we're evaluated on 1) the ideas we submit and 2) the comments we make, I think people assumed that 'My Feedback' would be based on comments. 

I do see value in having the ideas I've Unicorned. Perhaps renaming the title from 'My Feedback' to 'Ideas Unicorned'. Also creating a 'My Comments' section

**Comment by AVatch** [comment]
Greg and co have an admin dashboard where they can easily see, sort, and count your comments.

**Comment by AVatch** [comment]
account view has been updated
